### ISSUE TITLE
Add support for more Test Case attributes for Polarion

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/testimony#90]
Since we rely pretty heavily on `Testimony` to extract test case information in order to create/update/maintain them onto `Polarion`, I'd like to propose that we add support for the following additional attributes:

<img width="1191" alt="screenshot 2016-04-27 21 36 59" src="https://cloud.githubusercontent.com/assets/53362/14873057/3632eade-0cc0-11e6-80a8-e0fbcb674991.png">

* Level (these should match the different 'tiers' used by `Robottelo`)
  * 0 - Acceptance
  * 1 - Component
  * 2 - Integration
  * 3 - System
* Component
  * 0 - API
  * 1 - CLI
  * 2 - UI
* Type
  * 0 - Functional
  * 1 - Non-functional
  * 2 - Structural
* Pos/Neg
  * 0 - Positive
  * 1 - Negative
* Automation
  * 0 - Automated
  * 1 - Manual Only
  * 2 - Not Automated
* Importance
  * 0 - Low
  * 1 - Medium
  * 2 - High
  * 3 - Critical
* Upstream
  * 0 - Yes
  * 1 - No

**Comment by mbukatov** [comment]
I would suggest to reuse attribute ids as defined in fields definition xml configuration file of the template project (which should be reused in every project).

Eg. don't use `Component`, but `casecomponent` as the definition of the field looks like this:

	
	<fields>
		...
		<field description="A subsystem of the product or a packaged codebase " id="casecomponent" name="Component" type="enum:casecomponent"/>
		...
	</fields>

This way, you would not have to maintain a mapping between the name you would use in the testimony description of a test case and the polarion project attribute.

**Comment by elyezer** [comment]
We need a big decision here, are we making Testimony a tool for helping with Polarion or it should be something "generic" inspired by the fields present on Polarion?

If we decide to make Testimony a tool for helping with Polarion, then we should think on merging Betelgeuse and Testimony together otherwise we will end up with two tools to help with Polarion Testimony depending on Betelgeuse in order to fill information on Polarion and Betelgeuse depending on Testimony to extract information from the Docstrings. I know this is the case now, but currently Testimony is designed to be a generic parser for testcases docstrings.

About:

> Level (these should match the different 'tiers' used by Robottelo)
> 0 - Acceptance
> 1 - Component
> 2 - Integration
> 3 - System

I think we should leave for the user decide that and just parse the docstring instead of assuming some configuration. We may add some options like auto-level where the user will just need to define the tier and the level will be based on it.

**Comment by omaciel** [comment]
@elyezer agreed that the values themselves for the new attributes should be 'free form' and it is up to the user to provide whatever values are needed for his/her purpose.

As far as whether we should combine `Testimony` and `Betelgeuse`, it would be interesting to see who's using `Testimony` and what their uses are. For our team, I want to say that `Testimony` was designed with the ultimate goal of facilitating the management of our test cases through a third party tool (i.e. `Polarion`), whatever that tool may be, but is there really a need to combine it with `Betelgeuse`? What would be the benefits of doing so?

**Comment by elyezer** [comment]
@omaciel the main benefit I see is, when we need more fields like this issue we will require a related PR for Betelgeuse supporting that same set of fields. Since they are linked in some way and for every update on Testimony we will likely need a Betelgeuse update as well I think we should consider merging them.

**Comment by omaciel** [comment]
@elyezer let's see what @sthirugn has to say then.

**Comment by elyezer** [comment]
We already have some name options Betelgeuse + Testiomony = Betelmony and Testimony + Betelgeuse = Testigeuse :smile:

**Comment by sthirugn** [comment]
The main intent of making testimony in the first place is to be a test case respository tool making use of the test case docstrings.  So here are my thoughts:
- betelgeuse is polarion specific.  Testimony is a generic test case repository tool which should be easy enough to plug and play with any other test case management tool. I like to keep the testimony attributes list as short and relevant as possible to any project.  So -1 to combining betelgeuse and testimony.
- `Tags` attribute is primarily introduced in testimony to deal with this extensibility to any new attributes without modifying testimony code.  I think we should leverage testimony tags as much as possible for this request.
- `Component`, `Type`, `Pos/Neg`, `Automation`, `upstream` - can possibly be derived from the existing test case info.  Or we can use testimony tags for this.
- +1 to adding `level` and `Importance` as testimony attributes.  But I like to call it generic something like `Test Type` or `Type` and may be `Severity` so this can be applicable to any project in future.

**Comment by omaciel** [comment]
@sthirugn sounds like we may have to fork `Testimony` then...

**Comment by sthirugn** [comment]
@omaciel lets talk about this, I don't really see a need (atleast from what is mentioned in this issue) to forking or extending yet.

**Comment by elyezer** [comment]
I agree that we can leave Testimony as a separated project, but I think we should make it more generic to the point the user is able to specify what are the tags it expects. For example I would like to use Testimony to help me parse my docstring but I want to have some custom tag or change the name of a Testimony defined tag.

This way we can make Testimony not only suitable to some specific cases but for a even bigger set of application cases.

**Comment by sthirugn** [comment]
@elyezer :+1:
